blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/whizbangdevelopers/Qepton/wiki
    about: Check the documentation for help and guides
  - name: Discussions
    url: https://github.com/whizbangdevelopers/Qepton/discussions
    about: Ask questions and discuss ideas with the community
